development:
  adapter: postgresql
  host: localhost
  database: riddler_development
  username: riddler
  password: riddler
  pool: 5
  schema_search_path: public
  encoding: utf8
  timeout: 5000
  template: template0

test:
  adapter: postgresql
  host: localhost
  database: riddler_test
  username: riddler
  password: riddler
  pool: 5
  schema_search_path: public
  encoding: utf8
  timeout: 5000
  template: template0

